import { DashboardLayout } from '@/components/DashboardLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/lib/auth';
import { format } from 'date-fns';

export default function ManagerSavedQuotes() {
  const { user } = useAuth();

  const { data: assignedStaff } = useQuery({
    queryKey: ['assigned-staff', user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('staff_assignments')
        .select('staff_id')
        .eq('manager_id', user?.id);
      
      if (error) throw error;
      return data || [];
    },
    enabled: !!user?.id,
  });

  const { data: quotes, isLoading } = useQuery({
    queryKey: ['manager-staff-quotes', assignedStaff],
    queryFn: async () => {
      if (!assignedStaff || assignedStaff.length === 0) return [];
      
      const staffIds = assignedStaff.map(s => s.staff_id);
      const { data, error } = await supabase
        .from('quotes')
        .select('*')
        .in('created_by', staffIds)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data || [];
    },
    enabled: !!assignedStaff && assignedStaff.length > 0,
  });

  const { data: profiles } = useQuery({
    queryKey: ['staff-profiles-for-quotes', assignedStaff],
    queryFn: async () => {
      if (!assignedStaff || assignedStaff.length === 0) return [];
      
      const staffIds = assignedStaff.map(s => s.staff_id);
      const { data, error } = await supabase
        .from('profiles')
        .select('id, name')
        .in('id', staffIds);
      
      if (error) throw error;
      return data || [];
    },
    enabled: !!assignedStaff && assignedStaff.length > 0,
  });

  const getStaffName = (createdBy: string) => {
    return profiles?.find(p => p.id === createdBy)?.name || 'Unknown';
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Team Quotes</h1>
          <p className="text-muted-foreground">Quotes generated by your team members</p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>All Team Quotes</CardTitle>
            <CardDescription>View quotes from staff assigned to you</CardDescription>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <p className="text-muted-foreground">Loading...</p>
            ) : quotes && quotes.length > 0 ? (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Customer</TableHead>
                    <TableHead>Building</TableHead>
                    <TableHead>Total Amount</TableHead>
                    <TableHead>Created By</TableHead>
                    <TableHead>Date</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {quotes.map((quote) => (
                    <TableRow key={quote.id}>
                      <TableCell className="font-medium">{quote.customer_name}</TableCell>
                      <TableCell>{quote.building_name}</TableCell>
                      <TableCell>₹{Number(quote.total_amount).toLocaleString('en-IN')}</TableCell>
                      <TableCell>{getStaffName(quote.created_by)}</TableCell>
                      <TableCell>{format(new Date(quote.created_at), 'dd/MM/yyyy')}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            ) : (
              <p className="text-muted-foreground text-center py-4">
                No quotes from your team yet
              </p>
            )}
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
